language:
  - ruby

rvm:
  - "1.9.3"

<<<<<<< HEAD
script:
  - "./scripts/ci/katello_pr_$JOB.sh"

env:
  - JOB=rspec
  - JOB=minitest
  - JOB=headpin_rspec
  - JOB=cli
=======
before_install:
  - cp script/ci/katello.yml config/katello.yml

install:
  - travis_retry bundle install --without devboost:optional:debugging

script:
  - "./script/ci/katello_pr_$JOB.sh"

env:
  - JOB=minitest
  - JOB=rspec
  - JOB=headpin_rspec
<<<<<<< HEAD
>>>>>>> cf40be3dbfef9dce1fdd5ed8ca5273c35c9332f8
=======
  - JOB=other
>>>>>>> 42fd1e0a69d2ad9e0cb432e1ce553334428259cf
